"""Exporter for engines."""

from exporters.helpers import FileLikeProvider, AutoFormatter


def tabular_generator(engines):
    """Generator that produces rows for tabular formats (CSV) from the dict
    generated by export_engines.
    """

    cols = [
        'name',
        'makerrace',
        # 'description', # every value is "No information available"
        'size',
        'hull',
        'hull_integrated',
        'hull_threshold',
        'thrust_forward',
        'thrust_reverse',
        'thrust_strafe',
        'thrust_pitch',
        'thrust_yaw',
        'thrust_roll',
        'boost_thrust',
        'boost_duration',
        'boost_attack',
        'boost_release',
        'travel_thrust',
        'travel_charge',
        'travel_attack',
        'travel_release',
        'angular_pitch',
        'angular_roll',
    ]

    # output header
    yield ['id'] + cols

    # output data
    for engine_id in sorted(engines.keys()):
        engine = engines[engine_id]

        yield [engine_id] + [engine.get(col) for col in cols]


def export_engines(macro_db, destination=None, output_format='csv'):
    """Parses data about engines from the MacroDB and exports it.

    Arguments:
    macro_db: MacroDB into which engines were loaded.
    destination: output type and destination. Supported values:
                 - None: output to string and return it.
                 - string: interpreted as a file path. Writes the output to the
                           file and returns None.
                 - other: interpreted as file-like object. Writes the output to
                          it and returns None.
    output_format: format for outputting the data. See helper.AutoFormatter for
                   more details.
    """
    output = FileLikeProvider(destination)

    engines = {}

    for engine_id in macro_db.macros_by_type['engine']:
        engines[engine_id] = macro_db.macros[engine_id].properties

    formatter = AutoFormatter(output_format)
    with output as output_file:
        if formatter.is_tabular():
            formatter.output(tabular_generator(engines), output_file)
        elif formatter.is_structured():
            formatter.output(engines, output_file)
        else:
            raise ValueError('Unknown formatter type for format {}'
                             .format(output_format))

    return output.get_return()
